services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: qdrant-qa-api
    restart: unless-stopped
    volumes:
      - ./models:/app/models
    environment:
      - GPT4ALL_MODEL_PATH=/app/models
      - API_PORT=8000
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: qdrant-qa-bot
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_URL=http://api:8000