version: '3'

services:
  qa-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qdrant-qa-bot
    restart: unless-stopped
    volumes:
      - ./models:/app/models
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GPT4ALL_MODEL_PATH=/app/models